name: 11ty
on: [workflow_run]

jobs:
  build-deploy:
    runs-on:  ubuntu-latest

    strategy:
      matrix: 
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: yyyy
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
